---
federation:
  inbound:
    service-id-mapping:
    - from: "jfrou@*"
      to: "jfrou@01e49j78r7vs30xv5qb9mj5w52"
    - from: "jfmd@*"
      to: "jfmd@01e49j7a9f9sx346488s7y6rc7"
    - from: "jfrt@*"
      to: "jfrt@01e49j7nt5qc6w0satw40506g3"
    - from: "jffe@*"
      to: "jffe@000"
licenses:
- server-name: "83445bab5f1f"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "a25a48c41896"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "f4a81002ab39"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "ce7748b97ec4"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "d341d4b850ee"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "9a39cb09b316"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "0626da7bb99e"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "84aaf299c769"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "675df15c9597"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "2b65911f14eb"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "cb4d73b98a3b"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "c4b7c385ecd8"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "8d49900853d8"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "9cdea2b8f285"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "367132426e8c"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "24669acd876e"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "4f6f8074868c"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd05DMHlNbFF4Tnpvek9EbzFOUzR3TURkYUNtbGtPaUJrWlRBMk9ESmpPQzAwTm1VekxUUTBNak10\r\
    \nWWpoall5MDNZV1prWW1OaFptVmlPVGdLYjNkdVpYSTZJRUZrYm1Gd0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1ETXRNak5VTVRjNk16ZzZOVFV1TURBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogbHdYL2RuRGRGQWxIYUdyK2Rha2VZZkFwK1BneDRYN29MMUZScmZJNFBTUHhwZ2dL\r\
    \nckxsaXZmQUNIeVJHa256NHhEL0RnNGtqWUp4OG42UXB6WEtyU0pwZ2pPMVJoeWdvaHkydDJybXY5\r\
    \nYUMreGU1ZGlRUE9QR1NvVENWMjFGNFUwRHRvMDAwQU1xSkNwL3Y0a0RucFhJTHpOR2ZjeEZMc05L\r\
    \nM3YyVkZrSkVnOVZ4RHhHUWEzeUx2c0I1amdRVytGZVVnZy9yRXRzUk5oQXZBVnlaVVpuTStwK0Mz\r\
    \nQzNsUnVodEpsN0pnTHpoS0QxWmZBZ3JIT1pqK2RialVsTm1xSGZrNXhXRWxZZVByNkF1Qm9KM2lm\r\
    \nMUpMTDRlTE9HVklHa0hkWWZYcVczMkc4dlFtdVcxVzYweUlIdTIwSDlSZU5GSE9JeDRVbHFVMFZm\r\
    \nUEJ0aG9jbmVnPT0KdmVyc2lvbjogMQo=\r\n"
